project:
  type: book

book:
  title: "NLP Notes"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/nlp-notes
  site-url: https://nlp-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: Word2Vec
      chapters: 
        - "content/word2vec/w2v-song-rec.ipynb"
    - part: HF NLP
      chapters: 
        - "content/hf-nlp/tf-basic.ipynb"
        - "content/hf-nlp/tf-behind-pipe.ipynb"
        - "content/hf-nlp/tf-model.ipynb"
        - "content/hf-nlp/tf-tokenization.ipynb"
    

bibliography: references.bib

format:
  html:
    theme:
      - zephyrs
      - brand
    toc-depth: 4



